project:
  type: website
  output-dir: docs

website:
  title: "Alberto Martinezx"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - favourites.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

